export const LOAD_POPULAR_MOVIES = "LOAD_POPULAR_MOVIES";
export const LOAD_POPULAR_MOVIES_SUCCESS = "LOAD_POPULAR_MOVIES_SUCCESS";
export const LOAD_POPULAR_MOVIES_ERROR = "LOAD_POPULAR_MOVIES_ERROR";
